language: python

# Use container-base infrastructure
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: "3.7"
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: "3.8"
      dist: bionic
      sudo: required

install:
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
  - pip install codecov
  - pip install autopep8

before_script:
  # Stop the build if there are Python syntax errors or undefined names
  - flake8 .
  - autopep8 --diff --recursive --max-line-length 127 .

# Command to run tests
script:
  - nosetests --with-coverage tests/test-utils.py
  - nosetests --with-coverage tests/test-core.py
  - nosetests --with-coverage tests/test-output.py
  - nosetests --with-coverage tests/test-utils-conditions.py
  #  - 'nosetests tests/test-listall.py'
  #  - 'nosetests tests/test-rulesgenerator.py'
  #  - 'nosetests tests/test-utils.py'
  #  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && nosetests tests/test-utils_sns.py || false'
  - nosetests --with-coverage tests/test-main.py
  - nosetests --with-coverage tests/test-resources.py
  - nosetests --with-coverage tests/test-rules-ruleset.py
  - nosetests --with-coverage tests/test-rules-processingengine.py
  - nosetests --with-coverage --nocapture tests/test-scoutsuite.py -a "!credential"

# Update test coverage
after_success:
  - coveralls
  - codecov

